apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: banking-platform
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 8081
      targetPort: 8081
