# Default values for notification-service

replicaCount: 1

image:
  repository: notification-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi
