apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking-platform
  labels:
    app: transaction-service
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - port: 8082
      targetPort: 8082
