# Default values for transaction-service

replicaCount: 1

image:
  repository: transaction-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi
